apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guidellm-results
  namespace: llm-benchmark
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi
